---

version: '3'

services:
  app:
    build: .
    # container_name: task-manager-test2
    volumes:
      - .:/srv/task-manager
    ports:
      - 5001:5000
      - 8080:8080
    command: make start